services:
  elastic:
    container_name: elastic_container
    build: ./morfologik-elastic
    networks:
      - elastic
    ports:
      - 9200:9200
    mem_limit: 2GB
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD="qwerty"


networks:
  elastic:
    name: 'elastic-net'